//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int studentId { get; set; }
        public int classId { get; set; }
        public System.TimeSpan time { get; set; }
        public string actionPerformed { get; set; }
        public int teacherId { get; set; }
        public string roomId { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Room Room { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
